apiVersion: v2
name: flask-app
description: A Helm chart for Flask application with HPA on GKE
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - flask
  - python
  - hpa
  - gke
maintainers:
  - name: Platform Team
    email: platform@example.com